// Generated by Wrangler by running `wrangler types`

interface Env {
	hub: {"verify_token":"happy"};
	"wa-token": "EAAGi4kGYHd0BO3v07QXMZAoJFv0L1np90TQiZC3Fw3mkRdwBTl2xI3N6AgQaeDePQKGV66gbEsR3ahZAvx99MP8dcZBjS4hsZCbeubLyxeUjqhXoz6iVUJd3QEY3SZAZCxweX5n0aPuZA5FFnVtCTz0kNDAMPPKyJhzCbpZACie7pVulQEoNVTQmXh2h9jInLJRZAsjjQtsVXZBZClBgixU3oSuydcSNZCFZChBZC6vD8YZD";
	"wa-id": "410631452124211";
	openai: "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";
	resend: "re_gdQ3pYsW_9PucAGJnHJJBTTF9UTHqgoYD";
	UPSTASH_VECTOR_REST_URL: "https://immune-sawfly-28928-us1-vector.upstash.io";
	UPSTASH_VECTOR_REST_TOKEN: "ABcFMGltbXVuZS1zYXdmbHktMjg5MjgtdXMxYWRtaW5aV00zWmpJNE5URXRZV1V5WlMwMFpqQXpMV0ppWXpBdFkyVXdaV0kwTXpnMU5qQTA=";
	GEMINI: "AIzaSyBBeTifrChbrc2sZi0NI39nGWeZ_KjtHsQ";
	STORAGE_URL: "wt2.cloudcreatr.com";
	WT: R2Bucket;
	DB: D1Database;
}
