// Generated by Wrangler on Sun Aug 11 2024 14:30:42 GMT+0000 (Coordinated Universal Time)
// by running `wrangler types`

interface Env {
	hub: {"verify_token":"happy"};
	"wa-token": "EAAGi4kGYHd0BOZBsotPnh4ZAhccZBcFoZALMgyJQnyHR4T6ymTdzbjdLvefLcsjHtOxf8YbxMlj7ZBl7QzwxxhwknbkkkdlaXw5Ll2zV53X8JfZA2tgNcsuOWyAfg8ZAhJpcQgemyEAaOEujY8cZA0jcrrujYmxBiJbAs0AlkHGLptPZAFfVDLZA3oAYRnYkYIAfJsQs3R3mj4zs3bBlcWGZBRp6ZCHPm36Q";
	"wa-id": "410631452124211";
	openai: "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";
	DB: D1Database;
}
