// Generated by Wrangler on Wed Aug 14 2024 18:29:23 GMT+0000 (Coordinated Universal Time)
// by running `wrangler types`

interface Env {
	whatsapp_images: KVNamespace;
	hub: {"verify_token":"happy"};
	"wa-token": "EAAGi4kGYHd0BO9ZBC4yWxrDFIq79VUWtdc1jAnJqUmuAUpF5B2aZCZAu16sQjcNpKSCz4PJpjilwQSq0kb6lHck3NY3eaaHHXOmsrfj4dpqCcmpcQlAHXtgVeOxqnm48IePwtIS0nbMOcWIV9jqdzleL9pc2cD79pI4q9PfPJJsxtHwTtydB5iNywppuTTjkc5WtOPgNeF0Hn7ojbCgZAhE7ByGqr0MUt1KcaAVHalsZD";
	"wa-id": "410631452124211";
	openai: "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";
	resend: "re_gdQ3pYsW_9PucAGJnHJJBTTF9UTHqgoYD";
	UPSTASH_VECTOR_REST_URL: "https://immune-sawfly-28928-us1-vector.upstash.io";
	UPSTASH_VECTOR_REST_TOKEN: "ABcFMGltbXVuZS1zYXdmbHktMjg5MjgtdXMxYWRtaW5aV00zWmpJNE5URXRZV1V5WlMwMFpqQXpMV0ppWXpBdFkyVXdaV0kwTXpnMU5qQTA=";
	DB: D1Database;
	ATT: D1Database;
}
